### PR TITLE
Change comment behavior

### PR DESCRIPTION
**Pull request by snoopy**
* Include a space after comments
* If multiple lines are selected don't comment empty ones but still comment empty single lines

I'm not sure if this is the best way to do this so treat the code more like a suggestion.

### CODE REVIEW

**Comment by orbitalquark** [comment]
Thanks for the suggestions, however:

* I don't want to include spaces after comments because if you're using Textadept to edit existing code, you are expecting the existing code to have spaces too. In my experience this is frequently not the case.
* I prefer putting comments on empty lines because I can easily use my keybindings for `textadept.editing.select_paragraph()` in conjunction with `textadept.editing.toggle_comment()` to easily uncomment the block if I lose my selection (e.g. after a quick edit). Otherwise I'd have to manually select the block to uncomment and this is slow and potentially error prone.

Sorry :(

**Comment by orbitalquark** [comment]
I'd like to clarify my first bullet. When I say you are expecting the existing code to have spaces, I don't mean that you don't handle it (because your code does handle it). What I mean is that there is an inherent assumption that if there is a space after a comment, it would be consumed when turning off the comment. This may break code like Python that use spaces as indentation and a '#' was manually typed at the beginning of the line by someone.

I hope this is clear. Sorry for any confusion.

**Comment by snoopy** [comment]
I get the first point even though for me the current behavior breaks code indentation more often than not, which prompted the change request.
Maybe you could elaborate on the second point a bit?  
For example you have 3 separate paragraphs and select all of them (including the empty lines inbetween). You end up with one big paragraph that you can uncomment as a whole. However, you can no longer select the individual paragraphs easily to uncomment only one of them.  
You prefer to uncomment the merged paragraph over separate ones, correct? Just a matter of preference I guess.

Am I correct in assuming the easiest way to make this a personal change is to copy the entire function over to the `init.lua`?

**Comment by orbitalquark** [comment]
I see, sorry to hear that indentation is breaking more often than not for you :( Would the following in your *~/.textadept/init.lua* achieve the desired effect?

  for k, v in pairs(textadept.editing.comment_string) do
    textadept.editing.comment_string[k] = v .. ' '
  end

(Basically make the comment string have the extra space you desire.)

As for number 2, I find myself commenting out large blocks of code temporarily to test a feature or assumption, and then revert the comment, so paragraph selection is faster for me. It's rare that I comment out a block and then uncomment a smaller part of that block.

However, I am willing to investigate your solution for 2 further. I appreciate your questioning of some assumptions in my workflow :) I'll get back to you when I have some time.

**Comment by orbitalquark** [comment]
Oh, and to answer your question about the easiest way to make a personal change is indeed to copy the entire function and incorporate your modifications, at least for this case.

**Comment by orbitalquark** [comment]
A couple quick thoughts:

1. Not adding comments for blank lines may be as simple as this (haven't tested more thoroughly):

```
diff -r 7177375671cb modules/textadept/editing.lua
--- a/modules/textadept/editing.lua	Mon Jun 27 12:04:54 2022 -0400
+++ b/modules/textadept/editing.lua	Fri Jul 15 22:33:35 2022 -0400
@@ -365,6 +365,7 @@
   buffer:begin_undo_action()
   for line = s, not ignore_last_line and e or e - 1 do
     local p = buffer.line_indent_position[line]
+    if p == buffer.line_end_position[line] then goto continue end -- skip blank lines
     local uncomment = buffer:text_range(p, p + #prefix) == prefix
     if not uncomment then
       column = math.min(buffer.column[p], column)
@@ -380,6 +381,7 @@
     end
     if line == s then anchor = anchor + #suffix * (uncomment and -1 or 1) end
     if line == e then pos = pos + #suffix * (uncomment and -1 or 1) end
+    ::continue::
   end
   buffer:end_undo_action()
   anchor, pos = buffer.line_end_position[s] - anchor, buffer.length + 1 - pos
```

2. If you started with a commented out blank line and then toggle comments twice, you'd end up with an uncommented line. In the interest of consistency, this feels wrong to me, but of course that's just me. What do you think about it?

**Comment by snoopy** [comment]
Thanks for your feedback. I updated the code with that in mind. 

Regarding the behavior from your 2nd point.
<hr>
You start with a comment on an otherwise blank line:

```lua
--
```

<kbd>toggle comment</kbd>
<hr>
The comment is now gone:

```lua

```
<hr>


Toggling comment again makes the comment reappear
<kbd>toggle comment</kbd>

```lua
-- 
```
<hr>
This is what should happen. Did you observe something different? Do you expect something different?  
Maybe I am just conditioned by other lesser editors but this seems like the principle of least surprise to me (including the not commenting empty lines thing).  

I honestly thought comments are not working as intended. If you prefer it the way it works right now that is fine by me. The best thing about TA is being able to simply modify it to make it do what I want instead of it making me do what it wants.

**Comment by orbitalquark** [comment]
I observed something different when multiple lines are selected and you toggle comments.

For example:

  --foo()
  --
  --bar()

Select those three lines and toggle comment:

  foo()
  
  bar()

And again:

  --foo()
  
  --bar()

That feels wrong to me. The final state should be the same as the initial state after two toggles.

**Comment by snoopy** [comment]
The empty lines with spaces before the comment really tripped me up. Thanks for bringing it to light though. I'll look into this some more.

**Comment by snoopy** [comment]
I got turned around a bit while updating the code, should be fixed now.

Right now commenting works like this:

```lua
--foo()
  --
  --bar()
```
  
```lua
foo()
  
  bar()
```
  
```lua
-- foo()
  -- 
  -- bar()
```

So the end result looks like the starting point but with the added space after the comment prefix.   
Seems to work now so I'll close the PR. Thanks again for your assistance.

**Comment by M0JXD** [comment]
I like to have a space before the actual comment starts too, and was wondering if this could be revisited?

> for k, v in pairs(textadept.editing.comment_string) do textadept.editing.comment_string[k] = v .. ' ' end

This doesn't work as comment strings are provided by the lexers and the comment_string table starts empty. So far I have simply listed the languages I use most in my init.lua and added the space manually.

> I don't want to include spaces after comments because if you're using Textadept to edit existing code, you are expecting the existing code to have spaces too. In my experience this is frequently not the case.

This still rings true of course when entering some codebases. 
If there could be a setting for post-fixing the comment string with a space that would be handy, along with some logic to de-comment regardless of whether there's a space when toggling it, could possibly be auto-detected similar to how tabs/spaces work.

**Comment by orbitalquark** [comment]
Something like the following in your *~/.textadept/init.lua* should work:

```lua
events.connect(events.LEXER_LOADED, function(name)
  local prop = 'scintillua.comment.' .. name
  buffer[prop] = buffer[prop] .. ' ' -- extra trailing space
end)
```

**Comment by M0JXD** [comment]
> Something like the following in your _~/.textadept/init.lua_ should work:
> 
> ```lua
> events.connect(events.LEXER_LOADED, function(name)
>   local prop = 'scintillua.comment.' .. name
>   buffer[prop] = buffer[prop] .. ' ' -- extra trailing space
> end)
> ```

Thank you, `buffer` needs to be `buffer.property` but works great! Much appreciated.

```lua
events.connect(events.LEXER_LOADED, function(name)
    local prop = 'scintillua.comment.' .. name
    buffer.property[prop] = buffer.property[prop] .. ' ' -- extra trailing space
end)

```

**Pull request closed without merging**
